const products = [
    {
      _id: '1',
      name: 'BBT-Bentley-Continental-GTC-(2)',
      image: '/images/1.jpg',
      description:
        'A supercar – also called exotic car – is a loosely defined description of street-legal, high-performance luxury sports car. Since the 2000s or 2010s, the term hypercar has come into use for the highest performing supercars.',
      brand: 'Apple',
      category: 'Electronics',
      price: 89444.99,
      countInStock: 3,
      rating: 4.5,
      numReviews: 4,
    },
    {
      _id: '2',
      name: 'Benz',
      image: '/images/2.jpg',
      description:
        'A supercar – also called exotic car – is a loosely defined description of street-legal, high-performance luxury sports car. Since the 2000s or 2010s, the term hypercar has come into use for the highest performing supercars.',
      brand: 'Apple',
      category: 'Electronics',
      price: 593339.99,
      countInStock: 10,
      rating: 4.0,
      numReviews: 4,
    },
    {
      _id: '3',
      name: 'Mercedes-Benz G63 AMG Exterior',
      image: '/images/3.jpeg',
      description:
        'A supercar – also called exotic car – is a loosely defined description of street-legal, high-performance luxury sports car. Since the 2000s or 2010s, the term hypercar has come into use for the highest performing supercars.',
      brand: 'Cannon',
      category: 'Electronics',
      price: 923339.99,
      countInStock: 5,
      rating: 3,
      numReviews: 3,
    },
    {
      _id: '4',
      name: 'Beetel',
      image: '/images/4.jpg',
      description:
        'A supercar – also called exotic car – is a loosely defined description of street-legal, high-performance luxury sports car. Since the 2000s or 2010s, the term hypercar has come into use for the highest performing supercars.',
      brand: 'Sony',
      category: 'Electronics',
      price: 333399.99,
      countInStock: 10,
      rating: 5,
      numReviews: 3,
    },
    {
      _id: '5',
      name:'ferrari',
      image: '/images/5.jpg',
      description:
        'A supercar – also called exotic car – is a loosely defined description of street-legal, high-performance luxury sports car. Since the 2000s or 2010s, the term hypercar has come into use for the highest performing supercars.',
      brand: 'Logitech',
      category: 'Electronics',
      price: 49444.99,
      countInStock: 7,
      rating: 3.5,
      numReviews: 2,
    },
    {
      _id: '6',
      name: 'Aston Marteen',
      image: '/images/6.jpg',
      description:
        'A supercar – also called exotic car – is a loosely defined description of street-legal, high-performance luxury sports car. Since the 2000s or 2010s, the term hypercar has come into use for the highest performing supercars.',
      brand: 'Amazon',
      category: 'Electronics',
      price: 24449.99,
      countInStock: 0,
      rating: 4,
      numReviews: 4,
    },
    {
        _id: '7',
        name: '2017-Porsche-718-Cayman-Orange-1',
        image: '/images/7.jpg',
        description:
          'A supercar – also called exotic car – is a loosely defined description of street-legal, high-performance luxury sports car. Since the 2000s or 2010s, the term hypercar has come into use for the highest performing supercars.',
        brand: 'Amazon',
        category: 'Electronics',
        price: 29332.99,
        countInStock: 0,
        rating: 4,
        numReviews: 4,
      },
  
      {
        _id: '9',
        name: 'Msutang',
        image: '/images/9.jpg',
        description:
          'A supercar – also called exotic car – is a loosely defined description of street-legal, high-performance luxury sports car. Since the 2000s or 2010s, the term hypercar has come into use for the highest performing supercars.',
        brand: 'Amazon',
        category: 'Electronics',
        price: 2933333.99,
        countInStock: 0,
        rating: 4,
        numReviews: 4,
      },
      {
        _id: '10',
        name: 'Rolls Royce',
        image: '/images/10.jpg',
        description:
          'A supercar – also called exotic car – is a loosely defined description of street-legal, high-performance luxury sports car. Since the 2000s or 2010s, the term hypercar has come into use for the highest performing supercars.',
        brand: 'Amazon',
        category: 'Electronics',
        price: 233339.99,
        countInStock: 0,
        rating: 4,
        numReviews: 4,
      },
  ]
  
  export default products